# Generated by Django 4.1.3 on 2022-11-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
