# Generated by Django 4.1.3 on 2022-11-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_event', '0004_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, upload_to='user/uploads/avatar/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('', 'Select'), ('student', 'Student'), ('lectuerer', 'Lecturer'), ('staff', 'Staff')], max_length=45),
        ),
    ]
