# Generated by Django 4.1.3 on 2022-11-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_event', '0005_alter_customuser_avatar_alter_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(default='user/uploads/avatar/icon.png', upload_to='user/uploads/avatar/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=models.CharField(choices=[('student', 'Students'), ('lectuerer', 'Lecturers'), ('staff', 'Staff'), ('all', 'all')], max_length=90),
        ),
    ]
