# Generated by Django 4.1.3 on 2022-11-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_event', '0007_attendee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_attendees',
        ),
    ]
